### ISSUE TITLE
Peer Review #1-Content

### ISSUE THREAD

**Issue by Tierneygregory** [yxia1/WebTechProject#1]
First of all, I just want to say that I LOVE your website and I love the opening page and how it catches your eye! I think it go even further are really enrich your website you could Make the Voyages of Carrie more pronounced or in the final version you could even add animation or JavaScript on it which could be fun. And second I would love to maybe see lil descriptions below all the travel pictures to add a personal touch. But If that's not the vibe you're going for no worries!

**Comment by yxia1** [comment]
Thank you for your suggestion! I totally agree with you, and I will see how to incorporate it.
