### ISSUE TITLE
Peer Review: Content 

### ISSUE THREAD

**Issue by SoulJason** [yxia1/WebTechProject#4]
Hey! Wanted to start off by saying I the nav bar and layout of your website is clean! 

My two points of feedback for content on your site will be stated below!

1. Your about page seems to be super packed with information, and its hard to read due to spacing. I would either simplify the message you want to say, break it apart, or write a bit about the person behind the site too so people have a face behind the website.

![image](https://user-images.githubusercontent.com/25781284/230805233-280878cd-9d0e-4fa5-829b-ccf0e3a609d1.png)

2. I would also consider including more content on the locations and why you're recommending them on your website. Since they directly link outwardly, I have no idea why you're recommending me these locations or have any reason to stay on the site.

![image](https://user-images.githubusercontent.com/25781284/230805591-c0db33fd-1672-491b-a575-43086fc5e3c3.png)

**Comment by yxia1** [comment]
Thank you!
